#!/usr/bin/env node

var pick = require('./');

var choices = process.argv.slice(2);

if (choices.length === 0) {
  console.log('You can\'t pick from nothing.');
} else {
  console.log( pick(choices) );
}


